DROP DATABASE If EXISTS museum;

DROP TABLE IF EXISTS exhibitions CASCADE;
DROP TABLE IF EXISTS floors CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS rating_event;
DROP TABLE IF EXISTS support_event;
DROP TABLE IF EXISTS rating_value;
DROP TABLE IF EXISTS support_value;